
const fs = require('fs');
const path = require('path');

const vocabPath = path.join(__dirname, '../data/vocabulary.js');
let lines = fs.readFileSync(vocabPath, 'utf8').split('\n');

const patchData = {
    "ought": { pos: "aux", phrase: "ought to", example: "You ought to apologize." },
    "in spite of": { pos: "prep", phrase: "in spite of the rain", example: "We went out in spite of the rain." },
    "floating": { pos: "adj", phrase: "floating island", example: "It looks like a floating city." },
    "yard": { pos: "noun", phrase: "back yard", example: "The kids played in the yard." },
    "depress": { pos: "verb", phrase: "depress prices", example: "Bad news depressed the market." },
    "lord": { pos: "noun", phrase: "feudal lord", example: "He acted like a lord." },
    "accustomed": { pos: "adj", phrase: "accustomed to", example: "I am accustomed to hot weather." },
    "underlying": { pos: "adj", phrase: "underlying cause", example: "Stress is the underlying problem." },
    "refreshing": { pos: "adj", phrase: "refreshing drink", example: "A cold drink is refreshing." },
    "sinking": { pos: "adj", phrase: "sinking ship", example: "They abandoned the sinking ship." },
    "screaming": { pos: "noun", phrase: "screaming fans", example: "The screaming was loud." },
    "circumstances": { pos: "noun", phrase: "under the circumstances", example: "I did well under the circumstances." },
    "hemisphere": { pos: "noun", phrase: "northern hemisphere", example: "Japan is in the Northern Hemisphere." },
    "anthropologist": { pos: "noun", phrase: "cultural anthropologist", example: "She is a famous anthropologist." },
    "youngster": { pos: "noun", phrase: "lively youngster", example: "The park was full of youngsters." },
    "nursing": { pos: "noun", phrase: "nursing home", example: "She works in nursing." },
    "bullying": { pos: "noun", phrase: "stop bullying", example: "Bullying is a serious problem." },
    "emission": { pos: "noun", phrase: "carbon emission", example: "We must reduce emissions." },
    "density": { pos: "noun", phrase: "population density", example: "Tokyo has high population density." },
    "isolated": { pos: "adj", phrase: "isolated village", example: "He felt isolated and alone." },
    "entitle": { pos: "verb", phrase: "entitled to", example: "You are entitled to a refund." },
    "spinal": { pos: "adj", phrase: "spinal cord", example: "He suffered a spinal injury." },
    "mandatory": { pos: "adj", phrase: "mandatory meeting", example: "Attendance is mandatory." },
    "predominantly": { pos: "adv", phrase: "predominantly white", example: "The area is predominantly rural." },
    "innumerable": { pos: "adj", phrase: "innumerable stars", example: "There are innumerable possibilities." },
    "obsessed": { pos: "adj", phrase: "obsessed with", example: "He is obsessed with cars." },
    "detached": { pos: "adj", phrase: "detached house", example: "She felt detached from reality." },
    "wrecked": { pos: "adj", phrase: "wrecked car", example: "The ship was wrecked in the storm." },
    "preoccupied": { pos: "adj", phrase: "preoccupied with", example: "He seemed preoccupied." },
    "gigantic": { pos: "adj", phrase: "gigantic statue", example: "A gigantic wave hit the shore." },
    "slender": { pos: "adj", phrase: "slender figure", example: "She has long slender fingers." },
    "manifest": { pos: "verb", phrase: "manifest itself", example: "The symptoms manifested quickly." },
    "savage": { pos: "adj", phrase: "savage attack", example: "It was a savage beast." },
    "ingenious": { pos: "adj", phrase: "ingenious idea", example: "It was an ingenious solution." },
    "outraged": { pos: "adj", phrase: "outraged public", example: "Citizens were outraged by the tax." },
    "paralyzed": { pos: "adj", phrase: "paralyzed from waist down", example: "Fear paralyzed him." },
    "eminent": { pos: "adj", phrase: "eminent scholar", example: "He is an eminent scientist." },
    "secondhand": { pos: "adj", phrase: "secondhand smoke", example: "I bought a secondhand car." },
    "utmost": { pos: "adj", phrase: "utmost importance", example: "Safety is of the utmost importance." },
    "integral": { pos: "adj", phrase: "integral part", example: "Music is an integral part of my life." },
    "intricate": { pos: "adj", phrase: "intricate design", example: "The pattern is very intricate." },
    "intriguing": { pos: "adj", phrase: "intriguing question", example: "The idea is quite intriguing." },
    "merit": { pos: "noun", phrase: "on its own merit", example: "The plan has some merit." },
    "boundary": { pos: "noun", phrase: "boundary line", example: "We crossed the boundary." },
    "fossil": { pos: "noun", phrase: "fossil fuel", example: "Coal is a fossil fuel." },
    "hypothesis": { pos: "noun", phrase: "working hypothesis", example: "Her hypothesis was correct." },
    "mechanism": { pos: "noun", phrase: "mechanism of action", example: "The mechanism is broken." },
    "antibiotic": { pos: "noun", phrase: "antibiotic resistance", example: "Take the full course of antibiotics." },
    "famine": { pos: "noun", phrase: "famine relief", example: "The famine killed thousands." },
    "congress": { pos: "noun", phrase: "international congress", example: "He attended a medical congress." },
    "diversity": { pos: "noun", phrase: "cultural diversity", example: "We celebrate diversity." },
    "pioneer": { pos: "noun", phrase: "pioneer spirit", example: "He was a pioneer in radio." },
    "grocery": { pos: "noun", phrase: "grocery shopping", example: "I went to the grocery store." },
    "dialect": { pos: "noun", phrase: "speak a dialect", example: "The dialect is hard to understand." },
    "mammal": { pos: "noun", phrase: "marine mammal", example: "A whale is a mammal." },
    "protein": { pos: "noun", phrase: "high protein", example: "Meat is rich in protein." },
    "transplant": { pos: "noun", phrase: "kidney transplant", example: "The transplant was successful." },
    "shy": { pos: "adj", phrase: "shy person", example: "He is very shy." },
    "profound": { pos: "adj", phrase: "profound silence", example: "It had a profound effect." },
    "immune": { pos: "adj", phrase: "immune system", example: "He is immune to the virus." },
    "linguistic": { pos: "adj", phrase: "linguistic study", example: "She has linguistic talent." },
    "ugly": { pos: "adj", phrase: "ugly duckling", example: "The building is ugly." },
    "harsh": { pos: "adj", phrase: "harsh sentence", example: "The lighting is too harsh." },
    "random": { pos: "adj", phrase: "random choice", example: "Pick a card at random." },
    "adolescent": { pos: "noun", phrase: "adolescent years", example: "He is just an adolescent." },
    "elaborate": { pos: "adj", phrase: "elaborate plan", example: "The costume was elaborate." },
    "cognitive": { pos: "adj", phrase: "cognitive development", example: "Reading aids cognitive skills." },
    "seemingly": { pos: "adv", phrase: "seemingly endless", example: "It was seemingly easy." },
    "conform": { pos: "verb", phrase: "conform to", example: "You must conform to the rules." },
    "advocate": { pos: "noun", phrase: "advocate for", example: "She is an advocate for rights." },
    "thrive": { pos: "verb", phrase: "thrive on", example: "Children thrive on praise." },
    "provoke": { pos: "verb", phrase: "provoke a reaction", example: "Don't provoke the dog." },
    "dictate": { pos: "verb", phrase: "dictate a letter", example: "He dictated the terms." },
    "cite": { pos: "verb", phrase: "cite a source", example: "Please cite your sources." },
    "designate": { pos: "verb", phrase: "designated driver", example: "He was designated as leader." },
    "presume": { pos: "verb", phrase: "presume to know", example: "I presume you are busy." },
    "comprise": { pos: "verb", phrase: "comprised of", example: "The test comprises two parts." },
    "plunge": { pos: "verb", phrase: "plunge into", example: "She plunged into the water." },
    "induce": { pos: "verb", phrase: "induce labor", example: "Nothing could induce me to go." },
    "compel": { pos: "verb", phrase: "compel to go", example: "I was compelled to leave." },
    "comprehend": { pos: "verb", phrase: "comprehend fully", example: "I cannot comprehend it." },
    "refine": { pos: "verb", phrase: "refine skills", example: "We need to refine the process." },
    "render": { pos: "verb", phrase: "render service", example: "The blow rendered him unconscious." },
    "poll": { pos: "noun", phrase: "exit poll", example: "The poll predicts a win." },
    "norm": { pos: "noun", phrase: "social norm", example: "Deviation from the norm." },
    "disgust": { pos: "noun", phrase: "in disgust", example: "She turned away in disgust." },
    "premise": { pos: "noun", phrase: "basic premise", example: "The premise of the movie is simple." },
    "asset": { pos: "noun", phrase: "liquid asset", example: "Health is a great asset." },
    "lag": { pos: "noun", phrase: "time lag", example: "There is a lag in the video." },
    "counterpart": { pos: "noun", phrase: "female counterpart", example: "He met his counterpart." },
    "spectrum": { pos: "noun", phrase: "broad spectrum", example: "The colors of the spectrum." },
    "apt": { pos: "adj", phrase: "apt remark", example: "It was an apt description." },
    "entitled": { pos: "adj", phrase: "entitled to", example: "The book is entitled 'Hope'." },
    "obscure": { pos: "adj", phrase: "obscure reason", example: "The path was obscure." },
    "crude": { pos: "adj", phrase: "crude oil", example: "It was a crude attempt." },
    "liable": { pos: "adj", phrase: "liable to fall", example: "You are liable for the cost." },
    "synthetic": { pos: "adj", phrase: "synthetic fiber", example: "Nylon is synthetic." },
    "Muslim": { pos: "noun", phrase: "Muslim belief", example: "He is a Muslim." },
    "dispose": { pos: "verb", phrase: "dispose of", example: "Dispose of trash here." },
    "insert": { pos: "verb", phrase: "insert key", example: "Insert language here." },
    "awaiting": { pos: "verb", phrase: "awaiting trial", example: "We are awaiting news." },
    "cling": { pos: "verb", phrase: "cling to", example: "The child clung to his mother." },
    "surpass": { pos: "verb", phrase: "surpass the limit", example: "The results surpassed my hopes." },
    "portray": { pos: "verb", phrase: "portray hero", example: "The actor portrays a spy." },
    "soaring": { pos: "adj", phrase: "soaring prices", example: "The hawk was soaring high." },
    "migrate": { pos: "verb", phrase: "migrate south", example: "Whales migrate annually." },
    "exert": { pos: "verb", phrase: "exert pressure", example: "Don't exert yourself too much." },
    "accelerate": { pos: "verb", phrase: "accelerate speed", example: "The car accelerated." },
    "dwell": { pos: "verb", phrase: "dwell on", example: "Don't dwell on the past." },
    "reassure": { pos: "verb", phrase: "reassure him", example: "I reassured her it was safe." },
    "restrain": { pos: "verb", phrase: "restrain from", example: "He had to restrain himself." },
    "resent": { pos: "verb", phrase: "resent the fact", example: "I resent your tone." },
    "halt": { pos: "verb", phrase: "halt traffic", example: "The bus came to a halt." },
    "omit": { pos: "verb", phrase: "omit details", example: "Do not omit any names." },
    "accommodate": { pos: "verb", phrase: "accommodate request", example: "We can accommodate your needs." },
    "erase": { pos: "verb", phrase: "erase memory", example: "Erase the board please." },
    "inferred": { pos: "verb", phrase: "inferred from", example: "I inferred that he was angry." },
    "contemplate": { pos: "verb", phrase: "contemplate future", example: "She contemplated the painting." },
    "rotate": { pos: "verb", phrase: "rotate crops", example: "The fan rotates slowly." },
    "discard": { pos: "verb", phrase: "discard waste", example: "Discard the old ticket." },
    "incorporate": { pos: "verb", phrase: "incorporate into", example: "Mix and incorporate the flour." },
    "depict": { pos: "verb", phrase: "depict life", example: "The movie depicts war." },
    "disclose": { pos: "verb", phrase: "disclose secret", example: "He disclosed the truth." },
    "nurture": { pos: "verb", phrase: "nurture plant", example: "Nurture your talents." },
    "speculate": { pos: "verb", phrase: "speculate on", example: "Detectives speculate on motives." },
    "prolong": { pos: "verb", phrase: "prolong agony", example: "Don't prolong the meeting." },
    "offending": { pos: "adj", phrase: "offending remark", example: "Remove the offending item." },
    "drift": { pos: "verb", phrase: "drift away", example: "Snow drifted against the door." },
    "flourishing": { pos: "adj", phrase: "flourishing trade", example: "The plants are flourishing." },
    "coordinate": { pos: "verb", phrase: "coordinate efforts", example: "Colors coordinate well." },
    "combat": { pos: "verb", phrase: "combat disease", example: "Troops combat the enemy." },
    "fatigue": { pos: "noun", phrase: "combat fatigue", example: "She suffered from fatigue." },
    "illusion": { pos: "noun", phrase: "create illusion", example: "It is just an illusion." },
    "intake": { pos: "noun", phrase: "water intake", example: "Increase your fiber intake." },
    "offspring": { pos: "noun", phrase: "animal offspring", example: "She protects her offspring." },
    "self-esteem": { pos: "noun", phrase: "low self-esteem", example: "Build your self-esteem." },
    "odds": { pos: "noun", phrase: "against all odds", example: "The odds are in your favor." },
    "ratio": { pos: "noun", phrase: "ratio of 2 to 1", example: "Calculate the ratio." },
    "sentiment": { pos: "noun", phrase: "sentiment analysis", example: "Market sentiment is positive." },
    "bias": { pos: "noun", phrase: "unconscious bias", example: "He has a bias against it." },
    "domain": { pos: "noun", phrase: "domain name", example: "It is in the public domain." },
    "galaxy": { pos: "noun", phrase: "spiral galaxy", example: "Stars form a galaxy." },
    "criteria": { pos: "noun", phrase: "criteria for selection", example: "These are the criteria." },
    "surplus": { pos: "noun", phrase: "budget surplus", example: "We have a food surplus." },
    "primate": { pos: "noun", phrase: "higher primate", example: "Chimps are primates." },
    "diagnosis": { pos: "noun", phrase: "early diagnosis", example: "The diagnosis was cancer." },
    "antiquity": { pos: "noun", phrase: "classical antiquity", example: "Relics from antiquity." },
    "fraction": { pos: "noun", phrase: "small fraction", example: "Only a fraction remained." },
    "irony": { pos: "noun", phrase: "tragic irony", example: "The irony was lost on him." },
    "defect": { pos: "noun", phrase: "heart defect", example: "It is a genetic defect." },
    "erosion": { pos: "noun", phrase: "coastline erosion", example: "Prevent soil erosion." },
    "landmark": { pos: "noun", phrase: "famous landmark", example: "The statue is a landmark." },
    "dementia": { pos: "noun", phrase: "senile dementia", example: "He cares for patients with dementia." },
    "collision": { pos: "noun", phrase: "head-on collision", example: "Avoid a collision." },
    "cue": { pos: "noun", phrase: "take a cue", example: "That was my cue to leave." },
    "commodity": { pos: "noun", phrase: "hot commodity", example: "Time is a precious commodity." },
    "saint": { pos: "noun", phrase: "patron saint", example: "She is a saint." },
    "predator": { pos: "noun", phrase: "apex predator", example: "The owl is a predator." },
    "intervention": { pos: "noun", phrase: "medical intervention", example: "Early intervention helps." },
    "pesticide": { pos: "noun", phrase: "spray pesticide", example: "Pesticides kill bugs." },
    "kindergarten": { pos: "noun", phrase: "attend kindergarten", example: "She is in kindergarten." },
    "diabetes": { pos: "noun", phrase: "control diabetes", example: "Diabetes affects blood sugar." },
    "obesity": { pos: "noun", phrase: "fight obesity", example: "Obesity is rising." },
    "patent": { pos: "noun", phrase: "file a patent", example: "The invention has a patent." },
    "spouse": { pos: "noun", phrase: "spouse support", example: "Bring your spouse." },
    "epidemic": { pos: "noun", phrase: "opioid epidemic", example: "The flu was an epidemic." },
    "mortality": { pos: "noun", phrase: "infant mortality", example: "Mortality rates declined." },
    "beverage": { pos: "noun", phrase: "cold beverage", example: "Order a beverage." },
    "metabolism": { pos: "noun", phrase: "slow metabolism", example: "Sleep affects metabolism." },
    "fertile": { pos: "adj", phrase: "fertile land", example: "The soil is fertile." },
    "hostile": { pos: "adj", phrase: "hostile witness", example: "Don't be hostile." },
    "oriented": { pos: "adj", phrase: "detail oriented", example: "He is family oriented." },
    "splendid": { pos: "adj", phrase: "splendid view", example: "It was a splendid day." },
    "supreme": { pos: "adj", phrase: "supreme court", example: "Supreme power." },
    "superficial": { pos: "adj", phrase: "superficial wound", example: "The damage was superficial." },
    "fragile": { pos: "adj", phrase: "fragile item", example: "The glass is fragile." },
    "infinite": { pos: "adj", phrase: "infinite loop", example: "God is infinite." },
    "subsequent": { pos: "adj", phrase: "subsequent year", example: "Subsequent events proved him right." },
    "contaminated": { pos: "adj", phrase: "contaminated water", example: "The food was contaminated." },
    "restless": { pos: "adj", phrase: "restless sleep", example: "I felt restless." },
    "immense": { pos: "adj", phrase: "immense power", example: "The ocean is immense." },
    "metropolitan": { pos: "adj", phrase: "metropolitan museum", example: "It is a metropolitan city." },
    "solitary": { pos: "adj", phrase: "solitary confinement", example: "He leads a solitary life." },
    "collective": { pos: "adj", phrase: "collective bargaining", example: "It was a collective effort." },
    "diplomatic": { pos: "adj", phrase: "diplomatic immunity", example: "He was very diplomatic." },
    "explicit": { pos: "adj", phrase: "explicit lyrics", example: "Be explicit in your demands." },
    "sole": { pos: "adj", phrase: "sole survivor", example: "He is the sole heir." },
    "notable": { pos: "adj", phrase: "notable exception", example: "It was a notable success." },
    "affluent": { pos: "adj", phrase: "affluent area", example: "They are an affluent family." },
    "vocal": { pos: "adj", phrase: "vocal cord", example: "She was vocal about her rights." },
    "feminine": { pos: "adj", phrase: "feminine touch", example: "The dress is very feminine." },
    "rigid": { pos: "adj", phrase: "rigid structure", example: "He is rigid in his views." },
    "vulnerable": { pos: "adj", phrase: "vulnerable group", example: "The fort is vulnerable." },
    "spontaneous": { pos: "adj", phrase: "spontaneous applause", example: "It was spontaneous." },
    "per capita": { pos: "noun", phrase: "income per capita", example: "GDP per capita is high." },
    "inherent": { pos: "adj", phrase: "inherent danger", example: "Defects are inherent in the system." },
    "promising": { pos: "adj", phrase: "promising future", example: "He is a promising student." },
    "physiological": { pos: "adj", phrase: "physiological need", example: "Thirst is physiological." },
    "clinical": { pos: "adj", phrase: "clinical trial", example: "She has clinical depression." },
    "chronic": { pos: "adj", phrase: "chronic illness", example: "He has chronic pain." },
    "geological": { pos: "adj", phrase: "geological survey", example: "The geological features are unique." },
    "autonomous": { pos: "adj", phrase: "autonomous region", example: "Cars will be autonomous." },
    "drastically": { pos: "adv", phrase: "change drastically", example: "Prices fell drastically." },
    "thereby": { pos: "adv", phrase: "thereby hang a tail", example: "He signed, thereby agreeing." },
    "namely": { pos: "adv", phrase: "namely the following", example: "Two students, namely John and Sue." },
    "hence": { pos: "adv", phrase: "hence the name", example: "He is away, hence the delay." },
    "summon": { pos: "verb", phrase: "summon help", example: "He was summoned to court." },
    "lament": { pos: "verb", phrase: "lament the death", example: "She lamented her mistake." },
    "endowed": { pos: "verb", phrase: "endowed with", example: "He is endowed with talent." },
    "rejoice": { pos: "verb", phrase: "rejoice in", example: "They rejoiced at the news." },
    "allocate": { pos: "verb", phrase: "allocate time", example: "Allocate funds for the project." },
    "contend": { pos: "verb", phrase: "contend with", example: "He contends that he is innocent." },
    "discern": { pos: "verb", phrase: "discern the truth", example: "I could discern a figure." },
    "degrade": { pos: "verb", phrase: "degrade environment", example: "Materials degrade over time." },
    "frown": { pos: "verb", phrase: "frown upon", example: "She frowned at me." },
    "lure": { pos: "verb", phrase: "lure fish", example: "The shop lures customers in." },
    "stroll": { pos: "verb", phrase: "stroll in park", example: "We strolled along the beach." },
    "reconcile": { pos: "verb", phrase: "reconcile account", example: "They reconciled." },
    "comply": { pos: "verb", phrase: "comply with", example: "Comply with the order." },
    "pierce": { pos: "verb", phrase: "pierce ears", example: "The shriek pierced the air." },
    "hinder": { pos: "verb", phrase: "hinder growth", example: "Snow hindered travel." },
    "embody": { pos: "verb", phrase: "embody ideals", example: "He embodies the spirit." },
    "stalk": { pos: "verb", phrase: "stalk prey", example: "The lion stalked the deer." },
    "inflict": { pos: "verb", phrase: "inflict pain", example: "The storm inflicted damage." },
    "evacuated": { pos: "verb", phrase: "evacuate building", example: "Residents were evacuated." },
    "undone": { pos: "adj", phrase: "come undone", example: "His work was undone." },
    "poke": { pos: "verb", phrase: "poke fun", example: "Don't poke the bear." },
    "haunted": { pos: "adj", phrase: "haunted house", example: "The house is haunted." },
    "adhere": { pos: "verb", phrase: "adhere to", example: "Adhere to the plan." },
    "deteriorate": { pos: "verb", phrase: "health deteriorate", example: "Conditions deteriorated." },
    "inhibit": { pos: "verb", phrase: "inhibit shy", example: "Salt inhibits yeast." },
    "reap": { pos: "verb", phrase: "reap harvest", example: "You reap what you sow." },
    "affirm": { pos: "verb", phrase: "affirm faith", example: "He affirmed his support." },
    "immersed": { pos: "adj", phrase: "immersed in", example: "She was immersed in the book." },
    "expire": { pos: "verb", phrase: "expire date", example: "My license expired." },
    "embark": { pos: "verb", phrase: "embark on", example: "They embarked on a trip." },
    "undermine": { pos: "verb", phrase: "undermine authority", example: "Don't undermine me." },
    "pledge": { pos: "verb", phrase: "pledge money", example: "He pledged to help." },
    "distort": { pos: "verb", phrase: "distort image", example: "The mirror distorts." },
    "extinguish": { pos: "verb", phrase: "extinguish fire", example: "Firefighters extinguished the blaze." },
    "preach": { pos: "verb", phrase: "preach gospel", example: "Don't preach to me." },
    "curb": { pos: "verb", phrase: "curb inflation", example: "Curb your enthusiasm." },
    "withstand": { pos: "verb", phrase: "withstand pressure", example: "The walls withstood the flood." },
    "thrust": { pos: "verb", phrase: "thrust sword", example: "He thrust the papers at me." },
    "evoke": { pos: "verb", phrase: "evoke memory", example: "The smell evoked old memories." },
    "flatter": { pos: "verb", phrase: "flatter yourself", example: "The photo flatters you." },
    "textile": { pos: "noun", phrase: "textile mill", example: "Cotton is a textile." },
    "timber": { pos: "noun", phrase: "timber wolf", example: "The forest produces timber." },
    "riot": { pos: "noun", phrase: "riot police", example: "A riot broke out." },
    "apparatus": { pos: "noun", phrase: "lab apparatus", example: "Breathing apparatus." },
    "heir": { pos: "noun", phrase: "heir to throne", example: "He is the heir." },
    "equator": { pos: "noun", phrase: "on the equator", example: "It is hot near the equator." },
    "petroleum": { pos: "noun", phrase: "petroleum product", example: "Petroleum is drilled here." },
    "witch": { pos: "noun", phrase: "wicked witch", example: "The witch cast a spell." },
    "vapor": { pos: "noun", phrase: "water vapor", example: "Steam is water vapor." },
    "expertise": { pos: "noun", phrase: "technical expertise", example: "He has expertise in law." },
    "scorn": { pos: "noun", phrase: "pour scorn", example: "She looked at him with scorn." },
    "prophet": { pos: "noun", phrase: "prophet Isaiah", example: "A prophet predicts the future." },
    "sin": { pos: "noun", phrase: "commit a sin", example: "It is a sin to steal." },
    "cluster": { pos: "noun", phrase: "cluster bomb", example: "Flowers grow in a cluster." },
    "lump": { pos: "noun", phrase: "lump of coal", example: "A lump of sugar." },
    "meadow": { pos: "noun", phrase: "green meadow", example: "Cows grazed in the meadow." },
    "temperament": { pos: "noun", phrase: "artist temperament", example: "She has a calm temperament." },
    "chill": { pos: "noun", phrase: "chill wind", example: "There is a chill in the air." },
    "appliance": { pos: "noun", phrase: "home appliance", example: "Kitchen appliances." },
    "predecessor": { pos: "noun", phrase: "my predecessor", example: "He learned from his predecessor." },
    "entity": { pos: "noun", phrase: "legal entity", example: "The club is a separate entity." },
    "monarch": { pos: "noun", phrase: "British monarch", example: "The monarch ruled wisely." },
    "constraint": { pos: "noun", phrase: "time constraint", example: "Budget constraints." },
    "amendment": { pos: "noun", phrase: "constitutional amendment", example: "Pass an amendment." },
    "cosmos": { pos: "noun", phrase: "the cosmos", example: "Study the cosmos." },
    "hierarchy": { pos: "noun", phrase: "corporate hierarchy", example: "Move up the hierarchy." },
    "transaction": { pos: "noun", phrase: "bank transaction", example: "Complete the transaction." },
    "parasite": { pos: "noun", phrase: "parasite host", example: "Fleas are parasites." },
    "intuition": { pos: "noun", phrase: "woman intuition", example: "Trust your intuition." },
    "communist": { pos: "noun", phrase: "communist party", example: "He is a communist." },
    "legacy": { pos: "noun", phrase: "family legacy", example: "Leave a legacy." },
    "discourse": { pos: "noun", phrase: "political discourse", example: "Civil discourse." },
    "dairy": { pos: "noun", phrase: "dairy farm", example: "Milk is a dairy product." },
    "artifact": { pos: "noun", phrase: "ancient artifact", example: "Museum artifacts." },
    "apprehension": { pos: "noun", phrase: "feeling of apprehension", example: "He felt apprehension." },
    "melancholy": { pos: "noun", phrase: "melancholy mood", example: "Music makes me melancholy." },
    "specimen": { pos: "noun", phrase: "rock specimen", example: "Collect a specimen." },
    "tactics": { pos: "noun", phrase: "delay tactics", example: "Use tactical tactics." },
    "monopoly": { pos: "noun", phrase: "monopoly board", example: "It is a monopoly." },
    "token": { pos: "noun", phrase: "token of appreciation", example: "A small token." },
    "activist": { pos: "noun", phrase: "rights activist", example: "She is an activist." },
    "rhetoric": { pos: "noun", phrase: "empty rhetoric", example: "Ignore the rhetoric." },
    "census": { pos: "noun", phrase: "census data", example: "Take the census." },
    "verge": { pos: "noun", phrase: "on the verge", example: "Verge of tears." },
    "irrigation": { pos: "noun", phrase: "drip irrigation", example: "Crops need irrigation." },
    "coverage": { pos: "noun", phrase: "media coverage", example: "News coverage." },
    "cuisine": { pos: "noun", phrase: "local cuisine", example: "Try the cuisine." },
    "menace": { pos: "noun", phrase: "public menace", example: "He is a menace." },
    "peril": { pos: "noun", phrase: "in peril", example: "Lives act peril." },
    "autonomy": { pos: "noun", phrase: "regional autonomy", example: "Seek autonomy." },
    "cram": { pos: "verb", phrase: "cram school", example: "Cram for test." },
    "subsidy": { pos: "noun", phrase: "farm subsidy", example: "Apply for subsidy." },
    "empathy": { pos: "noun", phrase: "show empathy", example: "Have empathy." },
    "posture": { pos: "noun", phrase: "bad posture", example: "Fix your posture." },
    "duration": { pos: "noun", phrase: "long duration", example: "For the duration of the war." },
    "precaution": { pos: "noun", phrase: "safety precaution", example: "Take precautions." },
    "shortcoming": { pos: "noun", phrase: "admit shortcoming", example: "Everyone has shortcomings." },
    "psychiatrist": { pos: "noun", phrase: "see a psychiatrist", example: "Talk to a psychiatrist." },
    "subordinate": { pos: "noun", phrase: "my subordinate", example: "Treat subordinates well." },
    "vacuum": { pos: "noun", phrase: "vacuum pump", example: "In a vacuum." },
    "quest": { pos: "noun", phrase: "quest for fire", example: "Go on a quest." },
    "subscriber": { pos: "noun", phrase: "magazine subscriber", example: "New subscriber." },
    "rust": { pos: "noun", phrase: "rust bucket", example: "Iron turns to rust." },
    "proficiency": { pos: "noun", phrase: "language proficiency", example: "Test proficiency." },
    "latitude": { pos: "noun", phrase: "latitude and longitude", example: "High latitude." },
    "friction": { pos: "noun", phrase: "friction tape", example: "Reduce friction." },
    "botanist": { pos: "noun", phrase: "plant botanist", example: "She is a botanist." },
    "heredity": { pos: "noun", phrase: "heredity traits", example: "It is due to heredity." },
    "anatomy": { pos: "noun", phrase: "gray's anatomy", example: "Study anatomy." },
    "integrity": { pos: "noun", phrase: "man of integrity", example: "Keep your integrity." },
    "cargo": { pos: "noun", phrase: "cargo ship", example: "Load the cargo." },
    "bribe": { pos: "noun", phrase: "take a bribe", example: "Bribes are illegal." },
    "bulk": { pos: "noun", phrase: "bulk mail", example: "Buy in bulk." },
    "realm": { pos: "noun", phrase: "realm of possiblity", example: "King of the realm." },
    "plantation": { pos: "noun", phrase: "cotton plantation", example: "Work on a plantation." },
    "plow": { pos: "noun", phrase: "snow plow", example: "Plow the field." },
    "vending": { pos: "noun", phrase: "vending machine", example: "Vending machine." },
    "neuron": { pos: "noun", phrase: "brain neuron", example: "Neurons fire." },
    "vegetation": { pos: "noun", phrase: "dense vegetation", example: "Green vegetation." },
    "mutation": { pos: "noun", phrase: "gene mutation", example: "Mutation occurs." },
    "sewage": { pos: "noun", phrase: "sewage pipe", example: "Sewage system." },
    "paradigm": { pos: "noun", phrase: "paradigm shift", example: "New paradigm." },
    "protocol": { pos: "noun", phrase: "Kyoto protocol", example: "Follow protocol." },
    "accord": { pos: "noun", phrase: "peace accord", example: "Sign an accord." },
    "bureaucrat": { pos: "noun", phrase: "government bureaucrat", example: "Red tape bureaucrat." },
    "array": { pos: "noun", phrase: "array of", example: "An array of colors." },
    "clash": { pos: "noun", phrase: "clash of titans", example: "Colors clash." },
    "reign": { pos: "noun", phrase: "reign of terror", example: "During his reign." },
    "digit": { pos: "noun", phrase: "single digit", example: "Enter your digit." },
    "onset": { pos: "noun", phrase: "onset of winter", example: "Sudden onset." },
    "peasant": { pos: "noun", phrase: "peasant blouse", example: "Rich peasant." },
    "ultraviolet": { pos: "noun", phrase: "ultraviolet ray", example: "UV light." },
    "renowned": { pos: "adj", phrase: "renowned artist", example: "He is renowned." },
    "naive": { pos: "adj", phrase: "naive girl", example: "Don't be naive." },
    "vertical": { pos: "adj", phrase: "vertical blind", example: "Vertical line." },
    "wicked": { pos: "adj", phrase: "wicked witch", example: "That is wicked." },
    "subjective": { pos: "adj", phrase: "subjective view", example: "It is subjective." },
    "enlightened": { pos: "adj", phrase: "enlightened self", example: "Enlightened age." },
    "authentic": { pos: "adj", phrase: "authentic copy", example: "Authentic food." },
    "brutal": { pos: "adj", phrase: "brutal murder", example: "Life is brutal." },
    "static": { pos: "adj", phrase: "static IP", example: "Static cling." },
    "doomed": { pos: "adj", phrase: "doomed to fail", example: "We are doomed." },
    "innumerable": { pos: "adj", phrase: "innumerable ways", example: "Innumerable stars." },
    "aesthetic": { pos: "adj", phrase: "aesthetic sense", example: "Aesthetic appeal." },
    "obsessed": { pos: "adj", phrase: "obsessed by", example: "He is obsessed." },
    "detached": { pos: "adj", phrase: "detached retina", example: "Detached home." },
    "wrecked": { pos: "adj", phrase: "wrecked ship", example: "The plan was wrecked." },
    "reckless": { pos: "adj", phrase: "reckless driver", example: "Reckless act." },
    "preoccupied": { pos: "adj", phrase: "preoccupied mind", example: "He is preoccupied." },
    "gigantic": { pos: "adj", phrase: "gigantic step", example: "Gigantic size." },
    "conspicuous": { pos: "adj", phrase: "conspicuous place", example: "Make it conspicuous." },
    "slender": { pos: "adj", phrase: "slender thread", example: "Slender waist." },
    "manifest": { pos: "adj", phrase: "manifest destiny", example: "Manifest error." },
    "skeptical": { pos: "adj", phrase: "skeptical look", example: "I am skeptical." },
    "monotonous": { pos: "adj", phrase: "monotonous work", example: "Monotonous voice." },
    "savage": { pos: "adj", phrase: "savage beast", example: "Noble savage." },
    "juvenile": { pos: "adj", phrase: "juvenile court", example: "Juvenile behavior." },
    "prone": { pos: "adj", phrase: "prone to lie", example: "Prone position." },
    "arbitrary": { pos: "adj", phrase: "arbitrary rule", example: "Arbitrary arrest." },
    "ingenious": { pos: "adj", phrase: "ingenious device", example: "Ingenious mind." },
    "outraged": { pos: "adj", phrase: "outraged at", example: "He was outraged." },
    "intrinsic": { pos: "adj", phrase: "intrinsic factor", example: "Intrinsic motivation." },
    "paralyzed": { pos: "adj", phrase: "paralyzed fear", example: "Paralyzed legs." },
    "eminent": { pos: "adj", phrase: "eminent domain", example: "Eminent doctor." },
    "staple": { pos: "noun", phrase: "staple gun", example: "Staple diet." },
    "secondhand": { pos: "adj", phrase: "secondhand shop", example: "Secondhand news." },
    "indigenous": { pos: "adj", phrase: "indigenous people", example: "Indigenous plant." },
    "utmost": { pos: "adj", phrase: "utmost care", example: "Do your utmost." },
    "integral": { pos: "adj", phrase: "integral calculus", example: "Integral part." },
    "intricate": { pos: "adj", phrase: "intricate knot", example: "Intricate details." },
    "demographic": { pos: "noun", phrase: "demographic group", example: "Demographic trend." },
    "intact": { pos: "adj", phrase: "keep intact", example: "Arrived intact." },
    "intriguing": { pos: "adj", phrase: "intriguing title", example: "Very intriguing." },
    "perpetual": { pos: "adj", phrase: "perpetual motion", example: "Perpetual snow." },
    "spinal": { pos: "adj", phrase: "spinal tap", example: "Spinal column." },
    "susceptible": { pos: "adj", phrase: "susceptible host", example: "Susceptible to." },
    "mandatory": { pos: "adj", phrase: "mandatory sentencing", example: "It is mandatory." },
    "predominantly": { pos: "adv", phrase: "predominantly blue", example: "Predominantly male." }
};

let insideSys2000 = false;
let updatedCount = 0;

for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (line.trim().startsWith('sys_2000: [')) {
        insideSys2000 = true;
        continue;
    }
    if (insideSys2000 && line.trim().startsWith(']')) {
        insideSys2000 = false;
    }

    if (insideSys2000) {
        const wordMatch = line.match(/word:\s*"([^"]+)"/);
        if (wordMatch) {
            const word = wordMatch[1];
            if (patchData[word]) {
                const patch = patchData[word];
                let newLine = line;
                newLine = newLine.replace(/pos:\s*"[^"]*"/, `pos: "${patch.pos}"`);
                newLine = newLine.replace(/phrase:\s*"[^"]*"/, `phrase: "${patch.phrase}"`);
                newLine = newLine.replace(/example:\s*"[^"]*"/, `example: "${patch.example}"`);
                // If ref exists AND matches "sys_2000", remove it?
                // The issue was they had missing/unknown data.
                // We overwrite it.
                // Ref is handled by previous step (if ref existed and was valid, it was linked).
                // If checking loop here, presumably these items had NO ref or were not linked.
                // But just in case, we are fixing LOCAL data.

                lines[i] = newLine;
                updatedCount++;
            }
        }
    }
}

console.log(`Updated ${updatedCount} words in sys_2000.`);
fs.writeFileSync(vocabPath, lines.join('\n'));
